### ISSUE TITLE
Update Xamarin Forms CalendarCell Styling example

### ISSUE THREAD

**Issue by LanceMcCarthy** [telerik/xamarin-forms-docs#156]
The code example [in this documentation example](https://docs.telerik.com/devtools/xamarin/controls/calendar/styling/calendar-styling-cell#example) is out of date. It is using two deprecated approaches (both Telerik and Xamarin).

Pull Request with updated code has been submitted.

**Comment by kerpecheva** [comment]
Merged the pull request.
