### ISSUE TITLE
Bad slug in BarSeries docs

### ISSUE THREAD

**Issue by LanceMcCarthy** [telerik/xamarin-forms-docs#176]
In the note section that points to the common series properties, the slug-created URL is broken

https://docs.telerik.com/devtools/xamarin/controls/chart/series/cartesian/bar-series 

bad link

https://docs.telerik.com/devtools/xamarin/controls/chart/series/cartesian/%7B%slug%20chart-series-overview%20%%7D##features

**Comment by kerpecheva** [comment]
Fixed
