### ISSUE TITLE
Add link to register renderer

### ISSUE THREAD

**Issue by didiepetrova** [telerik/xamarin-forms-docs#35]
It is not clear the dev must register a renderer to get the content populated, unless he goes through the next articles as well.
A simple line with link to [the existing article](http://docs.telerik.com/devtools/xamarin/controls/sidedrawer/getting-started/sidedrawer-getting-started-register-renderer) would be great.

This has already been mentioned as a last step here: http://docs.telerik.com/devtools/xamarin/installation-and-deployment/windows/getting-started-windows

**Comment by PavelRPavlov** [comment]
with R2 there is no need to manually register renderers
